baseURL = 'https://decysif.fr'
languageCode = 'fr'
title = 'DéCySif'
copyright = 'OCamlPro'
SectionPagesMenu = "main"
site_logo = "/images/logo_decysif_excellence_for_security_white.svg"

theme = 'ananke'

DefaultContentLanguage = "fr"

Paginate = 10

[languages]

[languages.fr]
  weight = 1
  contentDir = "content/fr"
  languageCode = 'fr'
  [languages.fr.params]
    legal = "DéCySif est financé par l'appel à projet i-Démo et la région Ile-de-France."
[languages.en]
  weight = 1
  contentDir = "content/en"
  languageCode = 'en'
  [languages.en.params]
    legal = "DéCySif is a project funded by the i-Démo call and the Ile-de-France region."

[params]
  text_color = ""
  recent_posts_number = 5
[params.contact]
  development = "https://formspree.io/f/mayreylq"
