baseURL = 'https://decysif.fr'
languageCode = 'fr'
title = 'DéCySif'
copyright = 'OCamlPro'
SectionPagesMenu = "main"

theme = 'ananke'

DefaultContentLanguage = "fr"

Paginate = 10

[languages]
  [languages.fr]
    contentDir = "content/fr"
    languageCode = 'fr'
    weight = 1
    [languages.fr.params]
      legal = "DéCySif est financé par l'appel à projet i-Démo et la région Ile-de-France."
  [languages.en]
    contentDir = "content/en"
    languageCode = 'en'
    weight = 2
    [languages.en.params]
      legal = "DéCySif is a project funded by the i-Démo call and the Ile-de-France region."

[params]
  # TODO:
  # We probably need another way to integrate the logo to the navbar, or have a decent CSS handling for it
  # site_logo = '/images/logo_decysif_excellence_for_security_blank_bg.svg'
  text_color = ""
  recent_posts_number = 5
[params.contact]
  development = "https://formspree.io/f/mayreylq"
